[package]
name = "knot-desktop"
version = "0.0.1"
edition = "2024"
publish = false

[[bin]]
name = "knot"
path = "src/main.rs"

[dependencies]
cambium-genet-winit-host = { git = "https://github.com/merely-made/genet.git", rev = "e60fc879f4cfb3198ccdc3ff5713d02165af262b" }
knot-document = { path = "../../knot-document" }
layout-dom-api = { git = "https://github.com/merely-made/genet.git", rev = "e60fc879f4cfb3198ccdc3ff5713d02165af262b", version = "=0.1.0" }

[dev-dependencies]
genet-probe = { git = "https://github.com/merely-made/genet.git", rev = "e60fc879f4cfb3198ccdc3ff5713d02165af262b" }
tempfile = "3"
