[package]
name = "knot-desktop"
version = "0.0.1"
edition = "2024"
publish = false

[[bin]]
name = "knot"
path = "src/main.rs"

[dependencies]
cambium-genet-winit-host = { git = "https://github.com/merely-made/genet.git", rev = "138b6aca6e2795c6cad5162c0237f1882fddaa03" }
knot-document = { path = "../../knot-document" }
layout-dom-api = { git = "https://github.com/merely-made/genet.git", rev = "138b6aca6e2795c6cad5162c0237f1882fddaa03", version = "=0.1.0" }

[dev-dependencies]
genet-probe = { git = "https://github.com/merely-made/genet.git", rev = "138b6aca6e2795c6cad5162c0237f1882fddaa03" }
tempfile = "3"
